/**
 * Ordered safe capability probes (increasing risk).
 * Real private probes remain gated; financial writes never included.
 */

import { MEXC_CAPABILITY } from '../capabilityIds.js';

export const PROBE_RISK = Object.freeze({
  PUBLIC: 1,
  PRIVATE_READ: 2,
  TEST_ORDER: 3,
  WRITE: 99,
});

/** Approved fake/public probe definitions */
export const MEXC_PROBE_CATALOG = Object.freeze([
  {
    id: 'spot_ping',
    capabilityId: MEXC_CAPABILITY.MARKET_DATA_SPOT_PUBLIC,
    risk: PROBE_RISK.PUBLIC,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/ping',
    auth: 'none',
    timeoutMs: 5000,
    maxResponseBytes: 4096,
    persistFields: ['lastVerifiedAt', 'verificationState', 'latencyMs'],
  },
  {
    id: 'spot_time',
    capabilityId: MEXC_CAPABILITY.MARKET_DATA_SPOT_PUBLIC,
    risk: PROBE_RISK.PUBLIC,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/time',
    auth: 'none',
    timeoutMs: 5000,
    maxResponseBytes: 4096,
    persistFields: ['lastVerifiedAt', 'verificationState', 'latencyMs'],
  },
  {
    id: 'spot_exchange_info',
    capabilityId: MEXC_CAPABILITY.MARKET_DATA_SPOT_PUBLIC,
    risk: PROBE_RISK.PUBLIC,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/exchangeInfo',
    auth: 'none',
    timeoutMs: 8000,
    maxResponseBytes: 2_000_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'latencyMs'],
  },
  {
    id: 'futures_ping',
    capabilityId: MEXC_CAPABILITY.MARKET_DATA_FUTURES_PUBLIC,
    risk: PROBE_RISK.PUBLIC,
    method: 'GET',
    host: 'https://contract.mexc.com',
    path: '/api/v1/contract/ping',
    auth: 'none',
    timeoutMs: 5000,
    maxResponseBytes: 4096,
    persistFields: ['lastVerifiedAt', 'verificationState', 'latencyMs'],
  },
  {
    id: 'private_account',
    capabilityId: MEXC_CAPABILITY.PRIVATE_AUTH,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/account',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_ACCOUNT_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
  },
  {
    id: 'spot_open_orders',
    capabilityId: MEXC_CAPABILITY.SPOT_ORDER_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/openOrders',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_DEAL_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
    query: { symbol: 'BTCUSDT' },
  },
  {
    id: 'spot_my_trades',
    capabilityId: MEXC_CAPABILITY.SPOT_TRADE_HISTORY_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/myTrades',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_ACCOUNT_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
    query: { symbol: 'BTCUSDT', limit: 1 },
  },
  {
    id: 'wallet_currency_config',
    capabilityId: MEXC_CAPABILITY.WALLET_CURRENCY_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/capital/config/getall',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_WITHDRAW_READ',
    timeoutMs: 8000,
    maxResponseBytes: 1_000_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
  },
  {
    id: 'deposit_history',
    capabilityId: MEXC_CAPABILITY.DEPOSIT_HISTORY_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/capital/deposit/hisrec',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_WITHDRAW_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
    query: { limit: 1 },
  },
  {
    id: 'withdraw_history',
    capabilityId: MEXC_CAPABILITY.WITHDRAWAL_HISTORY_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/capital/withdraw/history',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_WITHDRAW_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
    query: { limit: 1 },
  },
  {
    id: 'transfer_history',
    capabilityId: MEXC_CAPABILITY.TRANSFER_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://api.mexc.com',
    path: '/api/v3/capital/transfer',
    auth: 'HMAC-SHA256',
    officialPermission: 'SPOT_TRANSFER_READ',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
    query: { fromAccountType: 'SPOT', toAccountType: 'FUTURES', page: 1, size: 1 },
  },
  {
    id: 'futures_assets',
    capabilityId: MEXC_CAPABILITY.FUTURES_ACCOUNT_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://contract.mexc.com',
    path: '/api/v1/private/account/assets',
    auth: 'futures_signature',
    officialPermission: 'Trade reading permission',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
  },
  {
    id: 'futures_open_positions',
    capabilityId: MEXC_CAPABILITY.FUTURES_POSITION_READ,
    risk: PROBE_RISK.PRIVATE_READ,
    method: 'GET',
    host: 'https://contract.mexc.com',
    path: '/api/v1/private/position/open_positions',
    auth: 'futures_signature',
    officialPermission: 'Trade reading permission',
    timeoutMs: 8000,
    maxResponseBytes: 256_000,
    persistFields: ['lastVerifiedAt', 'verificationState', 'keyGrant', 'lastFailureCode', 'sanitizedReason', 'latencyMs'],
    requiresLiveGate: true,
  },
]);

/** Explicitly excluded from orchestrator forever in this program without separate approval */
export const FORBIDDEN_PROBES = Object.freeze([
  { path: '/api/v3/order', reason: 'Real spot order' },
  { path: '/api/v3/order/test', reason: 'Test New Order requires separate real-provider approval' },
  { path: '/api/v3/capital/withdraw', reason: 'Withdrawal execute' },
  { path: '/api/v3/capital/transfer', method: 'POST', reason: 'Transfer execute' },
  { path: '/api/v1/private/order/submit', reason: 'Futures order' },
]);

export function listProbesByRisk(maxRisk = PROBE_RISK.PUBLIC) {
  return MEXC_PROBE_CATALOG.filter((p) => p.risk <= maxRisk);
}

export function getProposedRealReadOnlyProbes() {
  return MEXC_PROBE_CATALOG.filter((p) => p.requiresLiveGate);
}
