/**
 * Canonical runtime provenance for health/readiness observability.
 *
 * Trusted sources only (deployment-assigned):
 * 1. process.env.TITAN_RUNTIME_COMMIT  (inject at deploy/restart)
 * 2. backend/runtime-provenance.json   (generated by deploy script; not tracked)
 *
 * Intentionally does NOT treat ambient git HEAD of a dirty worktree as the
 * deployed implementation. Missing trusted markers → commit "unknown".
 *
 * Does not read or expose secrets.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** Only the TitanGold deploy-injected key — not ambient GIT_SHA from shells. */
const TRUSTED_ENV_KEYS = ['TITAN_RUNTIME_COMMIT'];

export const RUNTIME_PROVENANCE_FILENAME = 'runtime-provenance.json';

function normalizeCommit(raw) {
  if (raw == null) return null;
  const value = String(raw).trim();
  if (!value) return null;
  if (!/^[0-9a-f]{7,40}$/i.test(value)) return null;
  return value.toLowerCase();
}

function shortSha(sha) {
  return sha.length > 7 ? sha.slice(0, 7) : sha;
}

function backendRootFromModule() {
  // backend/utils → backend
  return path.resolve(__dirname, '..');
}

function defaultManifestPaths() {
  const paths = [];
  paths.push(path.join(backendRootFromModule(), RUNTIME_PROVENANCE_FILENAME));
  try {
    paths.push(path.join(process.cwd(), RUNTIME_PROVENANCE_FILENAME));
  } catch {
    /* ignore */
  }
  return [...new Set(paths)];
}

function readManifestFile(filePath) {
  try {
    if (!filePath || !fs.existsSync(filePath)) return null;
    const raw = fs.readFileSync(filePath, 'utf8');
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return null;
    const commit = normalizeCommit(
      parsed.implementationCommit || parsed.commit || parsed.TITAN_RUNTIME_COMMIT,
    );
    if (!commit) return null;
    return {
      commit: shortSha(commit),
      fullCommit: commit.length >= 40 ? commit : null,
      source: `manifest:${filePath}`,
      deployedAt: typeof parsed.deployedAt === 'string' ? parsed.deployedAt : null,
      environment: typeof parsed.environment === 'string' ? parsed.environment : null,
      sourcePath: typeof parsed.sourcePath === 'string' ? parsed.sourcePath : null,
      verified: true,
    };
  } catch {
    return null;
  }
}

/**
 * @param {NodeJS.ProcessEnv} [env]
 * @param {{
 *   manifestPaths?: string[],
 *   readManifestFn?: (p: string) => object|null,
 * }} [deps]
 */
export function resolveRuntimeProvenance(env = process.env, deps = {}) {
  for (const key of TRUSTED_ENV_KEYS) {
    const normalized = normalizeCommit(env[key]);
    if (normalized) {
      return {
        commit: shortSha(normalized),
        fullCommit: normalized.length >= 40 ? normalized : null,
        source: `env:${key}`,
        deployedAt: null,
        environment: null,
        sourcePath: null,
        verified: true,
      };
    }
  }

  const readFn = deps.readManifestFn || readManifestFile;
  const paths = deps.manifestPaths || defaultManifestPaths();
  for (const filePath of paths) {
    const fromFile = readFn(filePath);
    if (fromFile) return fromFile;
  }

  return {
    commit: 'unknown',
    fullCommit: null,
    source: 'unverified',
    deployedAt: null,
    environment: null,
    sourcePath: null,
    verified: false,
  };
}

let cached = null;

/**
 * Cached at first call for production env (no injectable deps).
 * Tests may call resetRuntimeProvenanceCache().
 */
export function getRuntimeProvenance(env = process.env, deps = {}) {
  const injectable = Boolean(deps.manifestPaths || deps.readManifestFn);
  if (!injectable && cached) return cached;
  const resolved = resolveRuntimeProvenance(env, deps);
  if (!injectable) cached = resolved;
  return resolved;
}

export function resetRuntimeProvenanceCache() {
  cached = null;
}

export function getRuntimeCommitShort(env = process.env, deps = {}) {
  return getRuntimeProvenance(env, deps).commit;
}
